---
tags: [rest,hateoas,data,react,security]
projects: [spring-data-rest,spring-data-jpa,spring-hateoas,spring-security,spring-boot,]
---
:toc: left
:icons: font
:source-highlighter: prettify
:image-width: 500

= React.js and Spring Data REST

This tutorial (https://spring.io/guides/tutorials/react-and-spring-data-rest/) shows a collection of apps that use Spring Data REST and its powerful backend functionality combined with React's sophisticated features to build an easy-to-grok UI.

* https://www.youtube.com/watch?v=TgCr7v9tdKM[Spring Data REST] provides a fast way to build hypermedia-powered repositories.
* http://facebook.github.io/react/index.html[React] is Facebook's solution to efficient, fast, and easy-to-use views in the land of JavaScript.

include::basic/README.adoc[leveloffset=+1]
include::hypermedia/README.adoc[leveloffset=+1]
include::conditional/README.adoc[leveloffset=+1]
include::events/README.adoc[leveloffset=+1]
include::security/README.adoc[leveloffset=+1]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]



# Tools
1. SpringBoot
2. Spring Data (CrudRepository)
3. H2 Database
4. Hibernate
5. Uses default Tomcat JDBC Connection Pool

# Supporting Website
https://spring.io/guides/gs/accessing-data-rest/  - This guide walks you through the process of creating an application that accesses relational JPA data through a hypermedia-based RESTful front end.

# Changes Made
1. In the Employee.java, removed @Data annotation which is tied to Lombok and replaced with setters/getters/toString().
2. Lombok appeared to be causing issue at runtime with no data showing in the UI.

# Summary
Tutorial comes as 5 projects (basic, conditional, events, hypermedia, and security).

Basic:
Started with Basic. Which is a simple react application that uses Spring Data via CrudRepository to retrieve some data from an H2 database.

app.js - in componentDidMount, retrieves all employees and assigns it to the employee array.

app.js.single-employee (rename app.js to app.js.original, rename this file to app.js) - in here the this.state is modified to capture a single employee and in componentDidMount we set each of these states.  This because the response JSON structure for a single employee is different then that of all employees.

Uses default Tomcat JDBC Connection Pool

# Execution

## Want to see your JavaScript changes automatically? 
Run npm run-script watch to put webpack into watch mode. It will regenerate bundle.js as you edit the source.

## URL
1. http://localhost:8080/ - componentDidMount will invoke and render /api/employees
2. To call the service api
    - To retrieve all employees (app.js) - http://localhost:8080/api/employees
    - To retrieve an employee by id - http://localhost:8080/api/employees/1

## H2 Database  (Edit Records)
1. To connect to H2 Database and edit/update records
          - http://localhost:8080/h2-console
          - use JDBC URL of jdbc:h2:mem:testdb
          - no password needed

## Postman - GET and POST additional records
POST: 
URL : http://localhost:8080/api/employees 
Headers:
	Key: Content-Type
  Value: application/json
  Body:
	      {"firstName": "Bilbo", 
	       "lastName": "Baggins", 
	       "description": "burglar"
	      }
	      
GET:
URL: http://localhost:8080/api/employees/2
